### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by ring-zl** [nii-yamagishilab/PartialSpoof#4]
ValueError: /data/***/PartialSpoof_countmeasure//modules/ssl_pretrain/wav2vec_small.pt is not a valid checkpoint since the required key: task_cfg is missing

**Comment by GeWanying** [comment]
Hi,

I met the same issue a few days before. Can you try to download the s3prl code from the link this repo re-directs [(here)](https://github.com/s3prl/s3prl/tree/7ab62aaf2606d83da6c71ee74e7d16e0979edbc3#installation) and install it manually, rather than installing the newest s3prl like `pip install s3prl`.

I guess this problem happens because this repo is built on a previous version of s3prl, and the way how s3prl loads wav2vec model changed a bit in the newest version. The exact codes are, the way PartialSpoof uses [here](https://github.com/s3prl/s3prl/blob/7ab62aaf2606d83da6c71ee74e7d16e0979edbc3/s3prl/upstream/wav2vec2/expert.py#L31C1-L31C89), and the way the newest s3prl version does [here](https://github.com/s3prl/s3prl/blob/main/s3prl/upstream/wav2vec2/expert.py#L23) and [here](https://github.com/s3prl/s3prl/blob/main/s3prl/upstream/wav2vec2/convert.py#L29).

**Comment by zlin0** [comment]
@ring-zl Hi, sorry for missing your issue. Please follow [Prepare](https://github.com/nii-yamagishilab/PartialSpoof/tree/main/03multireso#prepare) and install the [corresponding version](https://github.com/s3prl/s3prl/tree/7ab62aaf2606d83da6c71ee74e7d16e0979edbc3#installation) of s3prl as Wanying suggested. If you have any further questions, please feel free to ask here.
(Thanks Wanying!

**Comment by Abdullah-Eisa** [comment]
Hi @zlin0,

Having trouble setting up the conda environment for [Project Name]. Any guidance on recommended versions/configurations would be greatly appreciated!

Thanks,
